# Generated by Django 5.1.3 on 2025-03-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='name',
        ),
    ]
