# Generated by Django 5.1.3 on 2025-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0003_publication_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='color_theme',
            field=models.CharField(default='#5D3FD3', max_length=20),
        ),
    ]
