# Generated by Django 5.1.3 on 2025-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0004_alter_usuario_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cover',
            field=models.ImageField(default='cover_images/default_cover.jpg', upload_to='cover_images/'),
        ),
    ]
