# Generated by Django 5.1.3 on 2025-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0006_alter_usuario_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
