# Generated by Django 5.1.3 on 2025-09-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0008_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='background',
            field=models.CharField(default='#121212', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='background_divs',
            field=models.CharField(default='#1B1C1D', max_length=20),
        ),
    ]
