# Generated by Django 5.1.3 on 2025-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0009_usuario_background_usuario_background_divs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='background_divs',
        ),
        migrations.AddField(
            model_name='usuario',
            name='gradient_theme',
            field=models.CharField(default='#1B1C1D', max_length=20),
        ),
    ]
