# Generated by Django 5.1.3 on 2025-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0010_remove_usuario_background_divs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='background_divs',
            field=models.CharField(default='#1B1C1D', max_length=20),
        ),
    ]
