# Generated by Django 5.1.3 on 2025-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0011_usuario_background_divs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='platform_publication',
            field=models.CharField(choices=[('playstation', 'Playstation'), ('xbox', 'Xbox'), ('pc', 'PC'), ('nintendo', 'Nintendo'), ('mobile', 'Mobile')], default='pc', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='tag2',
            field=models.CharField(choices=[('help', 'Help'), ('bug', 'Bug'), ('funny', 'funny'), ('lpt', 'LPT'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='platform_user',
            field=models.CharField(choices=[('playstation', 'Playstation'), ('xbox', 'Xbox'), ('pc', 'PC'), ('nintendo', 'Nintendo'), ('mobile', 'Mobile')], default='pc', max_length=20),
        ),
    ]
