# Generated by Django 5.1.3 on 2026-03-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falaxart_app', '0013_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='background',
            field=models.CharField(default='#1B1C1D', max_length=20),
        ),
    ]
